### ISSUE TITLE
邮件认证的文案

### ISSUE THREAD

**Issue by noman798** [WildDogTeam/wilddog-issue#1]
修改建议
1. 使用中文标点（逗号）
2. 更加书面语化
3. 增加空行方便阅读
4.更加礼节化
5. 不要无谓的空格

以注册邮件为例

**现有的原始邮件**

你好,
 请点击下面链接完成邮件地址验证：
 %LINK% 
 如果你没有要验证邮件地址，请忽略此邮件。
 谢谢。
 %APPNAME%

**修改后的邮件**

修改部分加粗显示

**您**好**， 欢迎注册『%APPNAME%』**。

请点击下面链接完成邮件地址验证：

 %LINK% 

如果**您**没有**申请**注册，请忽略此邮件。

**另外，APPNAME建议用应用的项目名，比如『云资本』，而不是域名（如u88）**

**Comment by SinanWang** [comment]
get，已反馈
