### ISSUE TITLE
显示“”数据量过大，为了提高浏览器性能，当前数据为只读模式并且不能实时更新，请手动点开节点查看数据变化“可否在页面手动删除数据

### ISSUE THREAD

**Issue by SinanWang** [WildDogTeam/wilddog-issue#39]
这个情况下无法在预览中删除数据。 可以用sdk进行删除。

**Comment by ghost** [comment]
遇到这种情况基本上就是在使用野狗sdk的网站上,按F12,之后打开开发者控制台,实例一个wilddog对象ref,之后直接 ref.remove();

当然这些代码也可以写在用于测试的HTML文件里!
