### ISSUE TITLE
野狗微信怎么使用授权登录

### ISSUE THREAD

**Issue by SinanWang** [WildDogTeam/wilddog-issue#46]
在app后台里面找到微信的入口，找到正确的，然后把apikey这些填进去。

集成做法只需要两步：第一步，集成微信登录的SDK（包括到微信开发者公众平台一系列的申请***），第二步，集成野狗的SDK 。

**Comment by ghost** [comment]
具体的步骤是这样的:
1. 登录[微信开放平台](https://open.weixin.qq.com)注册帐号.应用类型的区别请查看微信开放平台的文档.这里不再多说了.
2. 应用注册好了之后微信会提供一个AppID和AppSecret,但是现在你把这个添入到野狗的帐号认证系统并不能登录成功,因为默认的微信应用只提供分享到朋友圈和分享给朋友这两个功能.所有别忘记申请开通微信登录功能!这点要注意!一定要注意!
   3.上面两部做好之后下面基本上就可以开搞了.Web应用直接套用JSAPI就可以有效果了,Android和iOS平台的可以按照楼上的的说明试一下.

另外,基本上第三方登录都是这一个套路.如果有疑问请继续评论!
