### ISSUE TITLE
安全域名白名单输入框和保存按钮点击的问题

### ISSUE THREAD

**Issue by lixplor** [WildDogTeam/wilddog-issue#52]
凑个热闹.

安全域名白名单中, 输入域名后, **必须按`回车`**, 输入的内容才生效, 保存按钮才可以点击. 
但是这个猜了很久才明白, 因为我只设置了一个域名, 所以根本想不到按`回车`, 所以保存按钮点了很久也不管用.
为什么不输入时就直接验证, 格式对的话就让保存按钮生效呢?

**Comment by plinkpaa** [comment]
收到，下个版本我们会做一些修正。
谢谢对野狗的支持😊
