### ISSUE TITLE
完成了一个野狗的命令行工具，用于更新规则

### ISSUE THREAD

**Issue by noman798** [WildDogTeam/wilddog-issue#61]
![image](https://cloud.githubusercontent.com/assets/12876555/18060089/ddc042ca-6e4e-11e6-96cb-384473bad136.png)

代码见 http://github.com/noman798/wdog
看看是不是官方发布一下

**Comment by ThinkingQuest** [comment]
我们正在review中。多谢你的贡献。

**Comment by stackOverMind** [comment]
已经放到
https://github.com/WildDogTeam/awesome-wilddog
列表中
