### ISSUE TITLE
如何从后台保证用户名的唯一性（比如类似微博的应用，用户名需要独一无二）

### ISSUE THREAD

**Issue by noman798** [WildDogTeam/wilddog-issue#63]
如何从后台保证用户名的唯一性（比如类似微博的应用，用户名需要独一无二）

**Comment by ghost** [comment]
唯一性这个问题是一个非常重要的功能，这个逻辑较多的功能其实还是需要放到服务器的后台来写，以前写J2EE的程序的时候，像这种唯一性的功能都是用Java代码来写，之后返回给前端页面来显示是否用户名唯一。当然，野狗这边好像可以在规则表达式中设置，我感觉 `exist()` 这个方法应该能帮到你！
