### ISSUE TITLE
修改用户名出错invalid_token

### ISSUE THREAD

**Issue by noman798** [WildDogTeam/wilddog-issue#64]
报错
invalid_token The supplied auth token was invalid

![image](https://cloud.githubusercontent.com/assets/12876555/18143888/a6aeebde-6ff6-11e6-9377-155f4f3b3ffc.png)

但是刷新页面，如上图，可以看到，当前并没有退出登录（可以拿到user对象）

**Comment by liaobinxu** [comment]
怎么联系你？

**Comment by noman798** [comment]
qq 375956667 @liaobinxu
