### ISSUE TITLE
请问是否有nativescript的支持计划?

### ISSUE THREAD

**Issue by Yi-Z0** [WildDogTeam/wilddog-issue#71]
如题.

**Comment by stackOverMind** [comment]
@YouYII 感谢你提高了我的视野，本来我还不知道有这个东西。是否支持取决于普及程度和可行性吧。如果 nativescript 发展迅速的话一定会想办法支持

**Comment by Yi-Z0** [comment]
@stackOverMind  谢谢你的回复, 我本来是看到 firebase 对 nativescript 有plugin, WildDog又跟 firebase 是兼容的,所以过来看看

**Comment by stackOverMind** [comment]
先关闭了，有问题再开
